<?php

/**
 * @file
 * Contains account.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function account_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the account module.
    case 'help.page.account':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides finance functionality.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function account_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'account/toolbar';
}

/**
 * Implements hook_theme().
 */
function account_theme()
{
  $theme['account'] = [
    'render element' => 'elements',
    'file' => 'account.page.inc',
    'template' => 'account',
  ];
  $theme['account_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'account.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function account_theme_suggestions_account(array $variables)
{
  $suggestions = [];
  $entity = $variables['elements']['#account'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'account__' . $sanitized_view_mode;
  $suggestions[] = 'account__' . $entity->bundle();
  $suggestions[] = 'account__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'account__' . $entity->id();
  $suggestions[] = 'account__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_views_data_alter().
 */
function account_views_data_alter(array &$data) {
  $data['withdraw']['state']['filter']['id'] = 'state_machine_state';
}

/**
 * Implements hook_locale_translation_projects_alter()
 * to alter correct the translation file path.
 *
 * @param $projects
 *
 * @return void
 */
function account_locale_translation_projects_alter(&$projects) {
  $projects['account']['info']['interface translation server pattern'] = __DIR__ . '/' . $projects['account']['info']['interface translation server pattern'];
}
