account.account_transfer_gateway.*:
  type: config_entity
  label: 'Transfer gateway config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: account.account_transfer_gateway.plugin.[%parent.plugin]

account.account_transfer_gateway.plugin.manual:
  type: mapping
