account.account_type.*:
  type: config_entity
  label: 'Account type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    withdraw_period:
      type: integer
      label: 'Withdraw period'
    minimum_withdraw:
      type: float
      label: 'Minimum withdraw limitation'
    maximum_withdraw:
      type: float
      label: 'Maximum withdraw limitation'

action.configuration.account_transfer_withdraw:
  type: mapping
  label: 'Action plugin config of account_transfer_withdraw'
  mapping:
