# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 获取用户的提现单列表

GET http://{{host}}/api/rest/views/account/withdraws/1?_format=json&created[min]=2018-01-01&created[max]=2018-05-12
Accept: application/json
Authorization: Basic {{username}} {{password}}

### 创建用户的转账方式

POST http://{{host}}/entity/account_transfer_method?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "type": "alipay",
  "transfer_gateway": "alipay",
  "name": "sdfsdf",
  "uid": "1",
  "alipay_name": "王哈哈",
  "alipay_account": "1267867@qq.com"
}

### 修改一个转账方式

PATCH http://{{host}}/admin/account/account_transfer_method/2?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "type": "alipay",
  "name": "sdfsdf",
  "alipay_name": "王哈哈",
  "alipay_account": "155555@qq.com"
}

### 获取用户的转账方式列表

GET http://{{host}}/api/rest/views/account/transfer-methods/1?_format=json
Accept: application/json
Authorization: Basic {{username}} {{password}}

### 获取用户的账户列表

GET http://{{host}}/api/rest/views/account/accounts/4?_format=json
Accept: application/json
Authorization: Basic {{username}} {{password}}

### 检查账户提现限制

GET http://{{host}}/api/rest/account/withdraw-limitation/2?_format=json
Accept: application/json
Authorization: Basic {{username}} {{password}}

### 申请请现

POST http://{{host}}/api/rest/account/apply-withdraw/1?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "amount": "0.00",
  "transfer_method": 2,
  "remarks": "用户输入的备注"
}

###


